apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: amirkhan20121999/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/notifications
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kraft-kafka:9092
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
