apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      nodePort: 30289
