apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
      nodePort: 30291