apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
      nodePort: 30288