apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS customers;
    CREATE DATABASE IF NOT EXISTS orders;
    CREATE DATABASE IF NOT EXISTS products;
    CREATE DATABASE IF NOT EXISTS payments;
    CREATE DATABASE IF NOT EXISTS notifications;
